services:
  - type: web
    name: cinecheck-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: cinecheck
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: CORS_ORIGINS
        value: https://cinecheckf.vercel.app,http://localhost:4200
      - key: PYTHON_VERSION
        value: 3.11.0

